### ISSUE TITLE
(Translate it and add) Hash function of multiple fields for trackBy

### ISSUE THREAD

**Issue by thekiba** [nycJSorg/30-seconds-of-angular#121]
`trackBy` принимает на вход `hash` функцию, соответственно можно написать любую свою. В самом простом понимании, мы просто возвращаем уже готовый примитив из объекта.

Если надо по нескольким полям, то делаем простую вещь:
— берем все необходимые поля
— конкатенируем

```typescript
trackBy(index: number, animal: Animal): string {
  return [ animal.name, animal.type, … ].join('🦊');
}
```

**Comment by kirjs** [comment]
# ngFor tracking by multiple fields

It's possible to track `ngFor` items by multiple fields by concatenating them:
```typescript
trackBy(index: number, animal: Animal): string {
  return [ animal.name, animal.type, … ].join('🦊');
}
```

**Comment by kirjs** [comment]
How about this?

**Comment by trinitiwowka** [comment]
```
trackBy(index: number, animal: Animal): string {
  return Object.values(animal).join('🦊');
}
```
