### ISSUE TITLE
buttons overflow

### ISSUE THREAD

**Issue by fetis** [nycJSorg/30-seconds-of-angular#124]
https://30.codelab.fun/accessing-all-nested-form-controls/

<img width="534" alt="Screen Shot 2019-06-03 at 18 12 17" src="https://user-images.githubusercontent.com/577042/58817089-386e9e00-862b-11e9-861d-7d330232ef11.png">

**Comment by NothingEverHappens** [comment]
Hide the buttons in the playground

**Comment by fetis** [comment]
it's not that easy. we use http://codelab.fun to display snippets in iframe, so this needs to be changed on codelab.fun. 
@kirjs what's your opinion? maybe create a separate playground for 30sec on the codelab?
